andrewhowdencom/interviewer:
  - AGENTS.md
  - docs/development

andrewhowdencom/announce:
  - AGENTS.md
  - docs/development

andrewhowdencom/ruf:
  - AGENTS.md
  - docs/development

andrewhowdencom/stdlib:
  - AGENTS.md
  - docs/development 

andrewhowdencom/vector:
  - AGENTS.md
  - docs/development
